#server.port=8080
#server.servlet.context-path=/book-now

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=Test_Home_VersionNew2;encrypt=false;
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
# Cloudinary Configuration
cloudinary.cloud-name=dun6cug7p
cloudinary.api-key=234973538287588
cloudinary.api-secret=K30KWUVPXLB6zpB2cmOkGG15RLQ
#spring.jpa.hibernate.ddl-auto=truncate